---
- hosts: containers
  gather_facts: false
  #  vars_files:
  #    - group_vars/core/vault.yml
  tasks:
  - name: provision
    delegate_to: 127.0.0.1
    community.general.proxmox:
      vmid: "{{ vmid }}"
      memory: "{{ memory }}"
      disk: "{{ disk }}"
      cpus: "{{ cpus }}"
      #      node: yourproxmoxnode
      node: dl
      #      api_user: "{{ proxmox_user }}@pam"
      #      api_password: "{{ proxmox_pass }}"
      api_user: "root@pam"
      api_password: "Mayil003"
      api_host: 192.168.1.156
      netif: '{"net0":"name=eth0,ip=dhcp,ip6=dhcp,bridge=vmbr0,tag=15,hwaddr={{ mac }}"}'
      password: labpass
      hostname: "{{ inventory_hostname }}"
      storage: "local-lvm"
      ostemplate: "local:vztmpl/debian-10-turnkey-core_16.0-1_amd64.tar.gz"
      timeout: 300
      #      pubkey: "your public key"
      onboot: no
