---
- hosts: containers
  gather_facts: false
  #  vars_files:
  #    - group_vars/core/vault.yml

  tasks:
  - name: remove
    delegate_to: 127.0.0.1
    community.general.proxmox:
      vmid: "{{ vmid }}"
      node: dl
      api_user: "root@pam"
      api_password: "Mayil003"
      api_host: 192.168.1.156
      state: absent
